AppBundle\Entity\Club:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ClubRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        phone:
            type: string
            length: '9'
        deletedAt:
            type: datetime
            column: deleted_at
        createdAt:
            type: datetime
            column: created_at
        updatedAt:
            type: datetime
            column: updated_at
    lifecycleCallbacks: {  }
