AppBundle\Entity\Player:
    type: entity
    table: player
    repositoryClass: AppBundle\Repository\PlayerRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
    manyToOne:
        club:
            targetEntity: AppBundle\Entity\Club
            inversedBy: players
            joinColumn:
              name: club_id
              referencedColumnName: id
    lifecycleCallbacks: {  }
